#!/usr/bin/env python3
"""Bounded setup operations: trusted code, target data, preflighted writes."""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
from pathlib import Path
import re
import stat
import sys
import tempfile

BUNDLE = Path(__file__).resolve().parent
GENERATED = "# Generated by scripts/sync-mcp-config.py"
KNOWN_PATHS = ("AGENTS.md", "CLAUDE.md", ".gitignore", ".mcp.json", ".agents/skills",
               ".claude/skills", ".codex/config.toml", "opencode.json", "scripts/sync-mcp-config.py")


def checked(root: Path, relative: str) -> Path:
    """Reject linked ancestors/leaves and special files before reading or writing.

    The sole permitted symlink is the canonical, in-target Claude skills link.
    Refuse even internal directory links so writes have one unambiguous owner.
    """
    parts = Path(relative).parts
    if not parts or Path(relative).is_absolute() or ".." in parts:
        raise ValueError(f"unsafe destination: {relative}")
    path = root
    for index, part in enumerate(parts):
        path = path / part
        if path.is_symlink():
            if (relative == ".claude/skills" and index == len(parts) - 1
                    and os.readlink(path) == "../.agents/skills"
                    and path.resolve().is_relative_to(root)):
                return path
            raise ValueError(f"symlink destination/ancestor refused: {relative}")
        if path.exists():
            mode = path.stat().st_mode
            if not (stat.S_ISREG(mode) or stat.S_ISDIR(mode)):
                raise ValueError(f"special file refused: {relative}")
            if index < len(parts) - 1 and not path.is_dir():
                raise ValueError(f"non-directory ancestor: {relative}")
    if not path.resolve().is_relative_to(root):
        raise ValueError(f"destination escapes target: {relative}")
    return path


def read(root: Path, relative: str) -> str:
    path = checked(root, relative)
    if not path.exists():
        return ""
    if not path.is_file() or path.stat().st_size > 5_000_000:
        raise ValueError(f"expected bounded text file: {relative}")
    return path.read_text(encoding="utf-8")


def renderer():
    # Only the installed, bundled renderer is imported; never target Python.
    spec = importlib.util.spec_from_file_location("bundled_renderer", BUNDLE / "templates/sync-mcp-config.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", nargs="?", choices=("bootstrap", "optimize", "audit", "apply"))
    parser.add_argument("--target", type=Path, default=Path.cwd())
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--harness", action="append", choices=("claude", "codex", "opencode"), default=[])
    parser.add_argument("--mcp", action="store_true", help="Opt in to MCP data/config rendering for selected harnesses; never starts servers")
    args = parser.parse_args()
    root = args.target.resolve()
    if not root.is_dir() or root in (Path(root.anchor), Path.home().resolve()):
        parser.error("target must be an existing project directory, not root/home")
    print(f"TARGET {root}")
    # Preflight the full known destination surface before *any* mutation.
    for relative in KNOWN_PATHS:
        checked(root, relative)
    mode = args.mode or ("optimize" if read(root, "AGENTS.md") else "bootstrap")
    writes: dict[str, str] = {}
    directories: set[str] = set()
    links: dict[str, str] = {}
    failures: list[str] = []

    def propose(relative: str, content: str, *, preserve: bool = False):
        existing = read(root, relative)
        if preserve and existing:
            return
        if existing != content:
            writes[relative] = content

    if mode == "bootstrap":
        propose("AGENTS.md", f"""# Shared Project Instructions

## Project

{root.name}. Inspect existing documentation before assuming a stack.

## Setup

Use documented install, run and test commands. Do not invent them.

## Core Rules

Preserve existing work and secrets. Ask before destructive actions or external writes beyond the request. Verify in proportion to risk and report unverified behavior.

## Context Loading

Load only instructions relevant to the current task. Keep simple requests simple.

## Skills

Use installed skills when scope matches. Integrations and review agents are optional.
""", preserve=True)
    elif not read(root, "AGENTS.md"):
        failures.append("AGENTS.md missing; run bootstrap explicitly")
    if mode in {"apply", "optimize"}:
        text = read(root, "AGENTS.md")
        clean = re.sub(r"<claude-mem-context>.*?</claude-mem-context>", "", text, flags=re.S)
        if text != clean:
            propose("AGENTS.md", clean)

    selected = set(args.harness)
    if mode == "audit":
        # Existing integrations may be inspected, but never installed by audit.
        selected.update(name for name, path in (("claude", "CLAUDE.md"), ("codex", ".codex/config.toml"),
                                               ("opencode", "opencode.json")) if checked(root, path).exists())
    if "claude" in selected:
        propose("CLAUDE.md", "@AGENTS.md\n\nShared rules belong in AGENTS.md.\n", preserve=True)
        directories.update((".agents/skills", ".claude"))
        link = checked(root, ".claude/skills")
        if not link.is_symlink():
            if link.exists():
                raise ValueError(".claude/skills is not a symlink; resolve manually")
            links[".claude/skills"] = "../.agents/skills"
    if "codex" in selected:
        directories.add(".codex")
    if "opencode" in selected and not args.mcp:
        propose("opencode.json", "{}\n", preserve=True)

    mcp_text = read(root, ".mcp.json")
    if args.mcp or (mode == "audit" and mcp_text):
        config = json.loads(mcp_text or '{"mcpServers": {}}')
        if not isinstance(config, dict) or not isinstance(config.get("mcpServers", {}), dict):
            raise ValueError("invalid MCP data: expected mcpServers object")
        servers = config.get("mcpServers", {})
        # Renderer supports stdio configurations only. Fail before writing rather
        # than silently discarding other transports or unsupported fields.
        for name, server in servers.items():
            if not isinstance(name, str) or not isinstance(server, dict):
                raise ValueError("invalid MCP server entry")
            if set(server) - {"command", "args", "env"} or not isinstance(server.get("command"), str):
                raise ValueError("bundled renderer supports stdio MCP command/args/env only")
            if not isinstance(server.get("args", []), list) or not all(isinstance(a, str) for a in server.get("args", [])):
                raise ValueError("MCP args must be strings")
            if not isinstance(server.get("env", {}), dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in server.get("env", {}).items()):
                raise ValueError("MCP env must map strings to strings")
        if args.mcp:
            propose(".mcp.json", '{"mcpServers": {}}\n', preserve=True)
        trusted = renderer()
        if "codex" in selected:
            expected = trusted.generate_codex(servers)
            existing = read(root, ".codex/config.toml")
            if existing and existing != expected and not existing.startswith(GENERATED):
                raise ValueError("non-generated Codex config differs; preserve and reconcile manually")
            propose(".codex/config.toml", expected)
        if "opencode" in selected:
            existing = json.loads(read(root, "opencode.json") or "{}")
            if not isinstance(existing, dict):
                raise ValueError("OpenCode configuration must be an object")
            existing["mcp"] = json.loads(trusted.generate_opencode(servers))["mcp"]
            propose("opencode.json", json.dumps(existing, indent=2) + "\n")

    # Validate all planned outputs (including type conflicts) before creating any.
    for relative in writes:
        path = checked(root, relative)
        if path.exists() and not path.is_file():
            raise ValueError(f"output is not a regular file: {relative}")
    for relative in directories:
        path = checked(root, relative)
        if path.exists() and not path.is_dir():
            raise ValueError(f"output is not a directory: {relative}")
    if mode == "audit":
        failures.extend(f"missing/drifted: {path}" for path in writes)
        failures.extend(f"missing link: {path}" for path in links)
        failures.extend(f"missing directory: {path}" for path in directories if not checked(root, path).exists())
        if len(read(root, "AGENTS.md").splitlines()) > 250:
            print("WARN AGENTS.md exceeds 250 lines; inspect actual task loading")
        for failure in failures:
            print(f"FAIL {failure}")
        print(f"Audit: {len(failures)} failure(s); destination code was not executed.")
        return int(bool(failures))
    if failures:
        raise ValueError("; ".join(failures))
    for relative in sorted(directories):
        path = checked(root, relative)
        if not path.exists():
            print(f"{'DRY mkdir' if args.dry_run else 'MKDIR'} {relative}")
            if not args.dry_run:
                path.mkdir(parents=True, exist_ok=True)
    for relative, content in writes.items():
        print(f"{'DRY write' if args.dry_run else 'WROTE'} {relative}")
        if args.dry_run:
            continue
        path = checked(root, relative)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Atomic replacement does not mutate another file through a hard link.
        fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(content)
            checked(root, relative)
            os.replace(temporary, path)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
    for relative, destination in links.items():
        print(f"{'DRY link' if args.dry_run else 'LINK'} {relative}")
        if not args.dry_run:
            checked(root, relative).symlink_to(destination, target_is_directory=True)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ValueError, OSError, TypeError) as exc:
        print(f"ERROR {exc}", file=sys.stderr)
        raise SystemExit(2)
