#!/usr/bin/env python3
"""Regenerate harness MCP config from the small default config plus profiles.

Run after every edit to .mcp.json. Never hand-edit the generated files.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MCP = ROOT / ".mcp.json"
CODEX = ROOT / ".codex" / "config.toml"
OPENCODE = ROOT / "opencode.json"
PROFILES = ROOT / ".mcp" / "profiles"


def _quote(s: str) -> str:
    return '"' + s.replace('"', '\\"') + '"'


def generate_codex(servers: dict) -> str:
    lines = ["# Generated by scripts/sync-mcp-config.py from .mcp.json. Do not hand-edit.", ""]
    for name, cfg in servers.items():
        command = cfg.get("command", "")
        args = cfg.get("args", [])
        env = cfg.get("env") or {}
        lines.append(f"[mcp_servers.{name}]")
        lines.append(f"command = {_quote(command)}")
        if args:
            joined = ", ".join(_quote(a) for a in args)
            lines.append(f"args = [{joined}]")
        if env:
            lines.append("[mcp_servers.%s.env]" % name)
            for k, v in env.items():
                lines.append(f"{k} = {_quote(str(v))}")
        lines.append("")
    return "\n".join(lines) + "\n"


def generate_opencode(servers: dict) -> str:
    out = {"mcp": {}}
    for name, cfg in servers.items():
        entry = {
            "type": "local",
            "command": [cfg.get("command", "")] + cfg.get("args", []),
            "enabled": True,
        }
        if cfg.get("env"):
            entry["environment"] = cfg["env"]
        out["mcp"][name] = entry
    return json.dumps(out, indent=2) + "\n"


def load_servers(profile_names: list[str]) -> dict:
    servers = json.loads(MCP.read_text(encoding="utf-8")).get("mcpServers", {})
    for name in profile_names:
        path = PROFILES / f"{name}.json"
        if not path.is_file():
            raise ValueError(f"unknown MCP profile: {name}")
        profile = json.loads(path.read_text(encoding="utf-8"))
        profile_servers = profile.get("mcpServers", {})
        collisions = set(servers) & set(profile_servers)
        if collisions:
            raise ValueError(f"profile {name} collides with default servers: {sorted(collisions)}")
        servers.update(profile_servers)
    return servers


def main() -> int:
    if not MCP.exists():
        print(f"ERROR {MCP} not found", file=sys.stderr)
        return 1
    profile_names = [arg.removeprefix("--profile=") for arg in sys.argv[1:] if arg.startswith("--profile=")]
    unexpected = [arg for arg in sys.argv[1:] if not arg.startswith("--profile=")]
    if unexpected:
        print(f"ERROR unsupported arguments: {unexpected}", file=sys.stderr)
        return 2
    try:
        servers = load_servers(profile_names)
    except (ValueError, json.JSONDecodeError) as error:
        print(f"ERROR {error}", file=sys.stderr)
        return 2
    CODEX.parent.mkdir(parents=True, exist_ok=True)
    CODEX.write_text(generate_codex(servers))
    OPENCODE.write_text(generate_opencode(servers))
    print(f"WROTE {CODEX.relative_to(ROOT)}")
    print(f"WROTE {OPENCODE.relative_to(ROOT)}")
    print(f"PROFILES {', '.join(profile_names) if profile_names else 'default only'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
